<?php
    $id = $_POST['id'];
    $student_id = mysqli_real_escape_string($con, $_POST['student_id']);
    $ft_id = $_POST['ft_id'];
    $income_year = $_POST['income_year'];
    $ft_id = $_POST['ft_id'];
    $dp_id = $_POST['dp_id'];
    $firstname_rumi = mysqli_real_escape_string($con, $_POST['firstname_rumi']);
    $lastname_rumi = mysqli_real_escape_string($con, $_POST['lastname_rumi']);
    $firstname_jawi = mysqli_real_escape_string($con, $_POST['firstname_jawi']);
    $lastname_jawi = mysqli_real_escape_string($con, $_POST['lastname_jawi']);
    $firstname_eng = mysqli_real_escape_string($con, $_POST['firstname_eng']);
    $lastname_eng = mysqli_real_escape_string($con, $_POST['lastname_eng']);
    $cityzen_id = mysqli_real_escape_string($con, $_POST['cityzen_id']);
    $birdth_date = mysqli_real_escape_string($con, $_POST['birdth_date']);
    $disease = mysqli_real_escape_string($con, $_POST['disease']);
    $father_name = mysqli_real_escape_string($con, $_POST['father_name']);
    $father_lastname = mysqli_real_escape_string($con, $_POST['father_lastname']);
    $father_job = mysqli_real_escape_string($con, $_POST['father_job']);
    $mother_name = mysqli_real_escape_string($con, $_POST['mother_name']);
    $mother_lastname = mysqli_real_escape_string($con, $_POST['mother_lastname']);
    $mother_job = mysqli_real_escape_string($con, $_POST['mother_job']);
    $email = mysqli_real_escape_string($con, $_POST['email']);
    $telephone = mysqli_real_escape_string($con, $_POST['telephone']);
    $ibtidai_graduate = mysqli_real_escape_string($con, $_POST['ibtidai_graduate']);
    $ibtidai_graduate_year = mysqli_real_escape_string($con, $_POST['ibtidai_graduate_year']);
    $mutawasit_graduate = mysqli_real_escape_string($con, $_POST['mutawasit_graduate']);
    $mutawasit_graduate_year = mysqli_real_escape_string($con, $_POST['mutawasit_graduate_year']);
    $sanawi_graduate = mysqli_real_escape_string($con, $_POST['sanawi_graduate']);
    $sanawi_graduate_year = mysqli_real_escape_string($con, $_POST['sanawi_graduate_year']);
    $down_graduate = mysqli_real_escape_string($con, $_POST['down_graduate']);
    $down_graduate_year = mysqli_real_escape_string($con, $_POST['down_graduate_year']);
    $first_highschool_graduate = mysqli_real_escape_string($con, $_POST['first_highschool_graduate']);
    $first_highschool_graduate_year = mysqli_real_escape_string($con, $_POST['first_highschool_graduate_year']);
    $second_highschool_graduate = mysqli_real_escape_string($con, $_POST['second_highschool_graduate']);
    $second_highschool_graduate_year = mysqli_real_escape_string($con, $_POST['second_highschool_graduate_year']);
    $melayu_lang_skill = mysqli_real_escape_string($con, $_POST['melayu_lang_skill']);
    $arab_lang_skill = mysqli_real_escape_string($con, $_POST['arab_lang_skill']);
    $ingris_lang_skill = mysqli_real_escape_string($con, $_POST['ingris_lang_skill']);
    $thai_lang_skill = mysqli_real_escape_string($con, $_POST['thai_lang_skill']);
    $certificate = mysqli_real_escape_string($con, $_POST['certificate']);
    $citizen_book = mysqli_real_escape_string($con, $_POST['citizen_book']);
    $id_book = mysqli_real_escape_string($con, $_POST['id_book']);
    $photo = mysqli_real_escape_string($con, $_POST['photo']);
    $password = mysqli_real_escape_string($con, $_POST['password']);
    $gender = mysqli_real_escape_string($con, $_POST['gender']);
    
    $update = mysqli_query($con, "UPDATE students SET     
           student_id='".$student_id."',
           income_year='".$income_year."',
           ft_id='".$ft_id."',
           dp_id='".$dp_id."',
           firstname_rumi='".$firstname_rumi."',
           lastname_rumi='".$lastname_rumi."',
           firstname_jawi='".$firstname_jawi."',
           lastname_jawi='".$lastname_jawi."',
           firstname_eng='".$firstname_eng."',
           lastname_eng='".$lastname_eng."',
           cityzen_id='".$cityzen_id."',
           birdth_date='".$birdth_date."',
           disease='".$disease."',
           father_name='".$father_name."',
           father_lastname='".$father_lastname."',
           father_job='".$father_job."',
           mother_name='".$mother_name."',
           mother_lastname='".$mother_lastname."',
           mother_job='".$mother_job."',
           email='".$email."',
           telephone ='".$telephone ."',
           ibtidai_graduate='".$ibtidai_graduate."',
           ibtidai_graduate_year='".$ibtidai_graduate_year."',
           mutawasit_graduate='".$mutawasit_graduate."',
           mutawasit_graduate_year='".$mutawasit_graduate_year."',
           sanawi_graduate='".$sanawi_graduate."',
           sanawi_graduate_year='".$sanawi_graduate_year."',
           down_graduate='".$down_graduate."',
           down_graduate_year='".$down_graduate_year."',
           first_highschool_graduate='".$first_highschool_graduate."',
           first_highschool_graduate_year='".$first_highschool_graduate_year."',
           second_highschool_graduate='".$second_highschool_graduate."',
           second_highschool_graduate_year='".$second_highschool_graduate_year."',
           melayu_lang_skill='".$melayu_lang_skill."',
           arab_lang_skill='".$arab_lang_skill."',
           ingris_lang_skill='".$ingris_lang_skill."',
           thai_lang_skill='".$thai_lang_skill."',
           certificate='".$certificate."',
           citizen_book='".$citizen_book."',
           id_book='".$id_book."',
           photo='".$photo."',
           password='".$password."',
           gender = '".$gender."'
           WHERE st_id='$id'");

?>
<br>
<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Berhasil!</strong> Data berhasil di perbaharui <a href="?page=student&&studentpage=edit&&id=<?= $id ?>" class="alert-link">Kilik untuk lihat</a>.
</div>
